package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/cocofhu/grasp/internal/config"
)

func main() {
	out := flag.String("out", "CONFIGURATION.md", "output markdown path")
	check := flag.Bool("check", false, "fail when generated file differs")
	flag.Parse()

	content := render()
	path := *out
	if !filepath.IsAbs(path) {
		path = filepath.Clean(path)
	}
	if *check {
		current, err := os.ReadFile(path)
		if err != nil || string(current) != content {
			fmt.Fprintf(os.Stderr, "%s is stale; run go run ./cmd/gen-configdoc\n", path)
			os.Exit(1)
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil && filepath.Dir(path) != "." {
		panic(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		panic(err)
	}
}

func render() string {
	var b strings.Builder
	b.WriteString(`# Configuration reference

Generated by ` + "`go run ./cmd/gen-configdoc`" + ` from the same option descriptors
used by the runtime. Do not edit this file manually.

Runtime precedence is explicit environment variable > YAML file > built-in
default. Sensitive values must not enter images, repositories, or public logs.

Git host credentials for sandboxes (` + "`GITHUB_*`" + ` / ` + "`GITLAB_*`" + ` / SSH) are
configured as project credentials, not in this platform config table.

| Environment variable | YAML path | Type | Default | Property | Description |
| --- | --- | --- | --- | --- | --- |
`)
	for _, option := range config.OptionDescriptors() {
		def := option.Default
		if def == "" {
			def = "Not set"
		}
		prop := "Public"
		if option.Sensitive {
			prop = "Sensitive"
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | `%s` | %s | %s |\n",
			option.Env, option.YAML, option.Type, def, prop, option.EN)
	}
	return b.String()
}
